class GardeningTerm {
  final String term;
  final String definition;
  final String details;
  final List<String> relatedTerms;
  final List<String> searchableVariations;

  const GardeningTerm({
    required this.term,
    required this.definition,
    required this.details,
    this.relatedTerms = const [],
    this.searchableVariations = const [],
  });
}

const List<GardeningTerm> gardeningTerms = [
  GardeningTerm(
    term: 'Bolting',
    definition: 'When a plant prematurely produces flowers and seeds, usually triggered by heat or stress.',
    details: 'Bolting is common in cool-season crops like lettuce, spinach, arugula, and cilantro when temperatures rise. Once a plant bolts, leaves typically become bitter and tough. The plant shifts energy from producing edible parts to reproduction. Prevention: plant at right season, provide shade, keep soil moist, choose bolt-resistant varieties, succession plant.',
    relatedTerms: ['Succession Planting', 'Cool-Season Crop'],
    searchableVariations: ['bolt', 'bolting', 'bolts'],
  ),
  GardeningTerm(
    term: 'Vernalization',
    definition: 'The requirement for a cold period to trigger flowering or bulb formation.',
    details: 'Many plants need exposure to cold temperatures (typically 32-50°F for several weeks) to complete their life cycle. This prevents them from flowering at the wrong time. Examples: garlic and onions need cold to form bulbs, artichokes need cold to produce buds, biennial vegetables like carrots need cold to flower in second year. In warm climates, some seeds can be refrigerated before planting.',
    relatedTerms: ['Hardening Off'],
    searchableVariations: ['vernalization', 'vernalize'],
  ),
  GardeningTerm(
    term: 'Side-Dress',
    definition: 'Applying fertilizer alongside growing plants during the growing season.',
    details: 'Side-dressing provides additional nutrients when plants need them most. Apply fertilizer in a band 4-6 inches from plant stems, then water in. Do this during active growth periods: when plants are knee-high (corn), when flowering begins (tomatoes, peppers), or monthly for heavy feeders (brassicas). Use compost, granular fertilizer, or liquid feed.',
    relatedTerms: ['Heavy Feeder', 'Nitrogen Fixation'],
    searchableVariations: ['side-dress', 'side-dressing', 'sidedress'],
  ),
  GardeningTerm(
    term: 'Curing',
    definition: 'Drying and hardening produce after harvest to improve storage life.',
    details: 'Curing toughens skins and concentrates sugars. Different crops need different conditions: Onions/garlic - warm, dry, airy place for 2-3 weeks until outer skins are papery. Potatoes - dark, cool (50-60°F), humid for 10-14 days to heal cuts. Winter squash/pumpkins - warm (75-85°F), dry for 10-14 days. Sweet potatoes - 85°F, 85% humidity for 5-7 days. Proper curing can extend storage from weeks to months.',
    relatedTerms: [],
    searchableVariations: ['cure', 'curing', 'cured'],
  ),
  GardeningTerm(
    term: 'Hilling',
    definition: 'Mounding soil up around the base of plants as they grow.',
    details: 'Hilling serves multiple purposes: Potatoes - covers developing tubers to prevent greening, increases yield. Leeks - blanches stems to increase tender white portion. Corn - provides stability against wind, encourages roots to grow from the stem. Brassicas - supports tall stems. Use a hoe to pull soil from pathways onto plant bases. Hill multiple times during season as plants grow.',
    relatedTerms: ['Blanching'],
    searchableVariations: ['hill', 'hilling'],
  ),
  GardeningTerm(
    term: 'Blanching',
    definition: 'Excluding light from developing vegetables to make them more tender and mild.',
    details: 'Blanching prevents chlorophyll production, reducing bitterness and creating pale, tender growth. Methods: tie outer leaves over cauliflower heads, hill soil around celery/leeks, grow under pots (endive), wrap stems (celery). Start 2-3 weeks before harvest. Blanched vegetables are sweeter and less fibrous but may have fewer nutrients. Not to be confused with blanching vegetables in boiling water for preservation.',
    relatedTerms: ['Hilling'],
    searchableVariations: ['blanch', 'blanching'],
  ),
  GardeningTerm(
    term: 'Mulching',
    definition: 'Covering soil surface with organic or inorganic material.',
    details: 'Mulch provides many benefits: retains moisture, suppresses weeds, moderates soil temperature, prevents soil splash on leaves, adds organic matter. Types: Organic - straw, wood chips, grass clippings, leaves, compost (breaks down over time). Inorganic - plastic, landscape fabric (permanent). Apply 2-4 inches deep, keeping mulch away from stems to prevent rot. Best time: after soil warms in spring (or immediately for fall crops).',
    relatedTerms: ['Compost'],
    searchableVariations: ['mulch', 'mulching'],
  ),
  GardeningTerm(
    term: 'Succession Planting',
    definition: 'Planting small amounts at regular intervals for continuous harvest.',
    details: 'Instead of planting all at once, plant every 1-3 weeks throughout the season. Ideal for: fast-maturing crops (radishes, lettuce, beans, cilantro), crops with short harvest windows, crops that bolt quickly. Benefits: avoid glut at harvest, extend season, maintain freshness. Plan: calculate days to maturity and work backward from first frost for fall crops. Some crops (tomatoes) don\'t need succession planting as they produce continuously.',
    relatedTerms: ['Bolting', 'Days to Maturity'],
    searchableVariations: ['succession plant', 'succession planting'],
  ),
  GardeningTerm(
    term: 'Transplanting',
    definition: 'Moving seedlings from one location to another, typically from indoors to garden.',
    details: 'Start seeds indoors for head start on season, then transplant outside after frost date. Process: 1) Harden off seedlings first. 2) Choose overcast day or evening. 3) Water seedlings well before moving. 4) Dig hole larger than root ball. 5) Handle by leaves, not stems. 6) Plant at same depth (except tomatoes - plant deeper). 7) Water thoroughly. 8) Protect from wind and sun for few days. Some plants (carrots, beans, dill) don\'t transplant well - direct sow instead.',
    relatedTerms: ['Hardening Off', 'Direct Sowing'],
    searchableVariations: ['transplant', 'transplanting'],
  ),
  GardeningTerm(
    term: 'Direct Sowing',
    definition: 'Planting seeds directly in the garden where they will grow.',
    details: 'Alternative to starting indoors and transplanting. Best for: root vegetables (carrots, radishes, beets), plants that don\'t like transplanting (beans, peas, dill, corn), succession crops, large seeds. Benefits: less work, no transplant shock, stronger roots. Tips: prepare soil well, plant at proper depth (2-3x seed width), keep moist until germination, thin seedlings to proper spacing. Some crops (tomatoes, peppers) should be started indoors in short-season climates.',
    relatedTerms: ['Transplanting', 'Thinning'],
    searchableVariations: ['direct sow', 'direct sowing'],
  ),
  GardeningTerm(
    term: 'Hardening Off',
    definition: 'Gradually acclimating indoor-grown seedlings to outdoor conditions.',
    details: 'Indoor seedlings are tender and will suffer if moved directly outside. Process takes 7-10 days: Day 1-2: place in shade outdoors for 2-3 hours. Day 3-4: increase to 4-5 hours, partial sun. Day 5-7: full day outside, bring in at night. Day 8-10: leave out overnight if above 50°F. Gradually increase sun, wind, and temperature exposure. Reduces watering slightly. Seedlings develop thicker cuticles and stronger stems. Critical step - don\'t skip it!',
    relatedTerms: ['Transplanting'],
    searchableVariations: ['hardening off', 'harden off', 'harden'],
  ),
  GardeningTerm(
    term: 'Thinning',
    definition: 'Removing excess seedlings to give remaining plants proper space.',
    details: 'Seeds are often sown thickly to ensure germination. Thinning prevents overcrowding which causes: poor air circulation, disease, competition for nutrients, small/weak plants. When to thin: when seedlings have 2-3 true leaves. How: snip unwanted seedlings at soil level with scissors (don\'t pull - damages neighbors\' roots), or gently pull if soil is loose. Spacing: follow seed packet recommendations. Many thinnings are edible: beet greens, baby lettuce, micro carrots.',
    relatedTerms: ['Direct Sowing'],
    searchableVariations: ['thin', 'thinning'],
  ),
  GardeningTerm(
    term: 'Pinching',
    definition: 'Removing the growing tip of a plant to encourage bushier growth.',
    details: 'Pinching stimulates side branches by removing apical dominance. Use thumb and finger to pinch off top 1/4 - 1/2 inch of stem. When to pinch: Basil - pinch frequently above leaf pairs to prevent flowering. Petunias, coleus - pinch when young for bushiness. Tomatoes - pinch suckers on indeterminate varieties. Peppers - pinch early flowers for stronger plants. Result: bushier, fuller plants with more growing points and better yields.',
    relatedTerms: ['Pruning', 'Suckers'],
    searchableVariations: ['pinch', 'pinching'],
  ),
  GardeningTerm(
    term: 'Pruning',
    definition: 'Selectively removing plant parts to improve health, shape, or productivity.',
    details: 'Pruning improves air circulation, directs energy to fruit production, and maintains plant size. Types: Heading cuts - remove tip of branch (encourages branching). Thinning cuts - remove entire branch at base (opens up plant). When to prune: Tomatoes - remove suckers and lower leaves. Fruit trees - dormant season. Herbs - harvest regularly. Perennials - remove dead/diseased wood. Use clean, sharp tools. Make cuts at 45° angle just above bud or branch junction.',
    relatedTerms: ['Pinching', 'Suckers'],
    searchableVariations: ['prune', 'pruning'],
  ),
  GardeningTerm(
    term: 'Suckers',
    definition: 'Side shoots that grow between the main stem and branches, mainly on tomatoes.',
    details: 'Suckers emerge from leaf axils (where leaf meets stem) on tomato plants. For indeterminate (vining) tomatoes: removing suckers focuses energy on fruit production, improves air circulation, and makes management easier. Pinch when small (2-4 inches). Leave 1-2 main stems. For determinate (bush) tomatoes: don\'t remove suckers - they produce fruit! Also applies to: fruit tree water sprouts, raspberry canes growing outside row.',
    relatedTerms: ['Pinching', 'Pruning', 'Indeterminate'],
    searchableVariations: ['sucker', 'suckers'],
  ),
  GardeningTerm(
    term: 'Inoculating',
    definition: 'Applying beneficial bacteria to seeds or soil to help plants grow.',
    details: 'Most common: Rhizobium bacteria for legumes (beans, peas, clover). These bacteria colonize root nodules and convert atmospheric nitrogen into plant-available form (nitrogen fixation). Benefits: stronger plants, increased yields, improved soil, reduced fertilizer needs. How to use: coat seeds with powder before planting, or mix granular form into soil. Different legume types need different inoculant strains. Inoculant has shelf life - buy fresh each year.',
    relatedTerms: ['Nitrogen Fixation'],
    searchableVariations: ['inoculate', 'inoculating'],
  ),
  GardeningTerm(
    term: 'Scapes',
    definition: 'The flowering stalk that emerges from garlic and some onions.',
    details: 'Hardneck garlic produces curling flower stalks (scapes) in late spring/early summer. Should be removed to direct energy to bulb development - increases bulb size by 25-30%. Harvest when scapes curl and before they straighten. Scapes are edible and delicious: mild garlic flavor, tender texture. Uses: pesto, stir-fries, grilled, pickled. Consider it a bonus crop! Softneck garlic doesn\'t produce scapes. Some onions also produce scapes - also remove them.',
    relatedTerms: [],
    searchableVariations: ['scapes', 'scape'],
  ),
  GardeningTerm(
    term: 'Heavy Feeder',
    definition: 'Plants that require large amounts of nutrients to grow well.',
    details: 'Heavy feeders deplete soil nutrients quickly and need regular fertilization. Examples: tomatoes, peppers, corn, squash, brassicas, cucumbers. Care: add lots of compost before planting, side-dress monthly with fertilizer, rotate with light feeders and nitrogen-fixing crops. Use balanced fertilizer or specific to needs (high nitrogen for leafy growth, phosphorus for roots/flowers). Signs of deficiency: yellowing leaves, poor growth, small fruits.',
    relatedTerms: ['Side-Dress', 'Crop Rotation', 'Compost', 'Nitrogen Fixation'],
    searchableVariations: ['heavy feeder', 'heavy feeders'],
  ),
  GardeningTerm(
    term: 'Days to Maturity',
    definition: 'The number of days from planting (or transplanting) until harvest.',
    details: 'Counts from: Direct-sown crops - from seeding date. Transplanted crops - from transplant date (add 4-8 weeks for indoor growing time). Perennials - from planting bare root/crown. These are averages - actual time varies with weather, soil, and care. Use to: plan succession plantings, calculate last planting date before frost, choose varieties for your season length. Short-season climates need fast-maturing varieties.',
    relatedTerms: ['Succession Planting', 'Frost Date'],
    searchableVariations: ['days to maturity'],
  ),
  GardeningTerm(
    term: 'Cool-Season Crop',
    definition: 'Vegetables that grow best in cool weather and tolerate light frost.',
    details: 'Prefer temperatures 60-70°F, many tolerate frost to 25-28°F. Plant in early spring or fall. Bolt (go to seed) in hot weather. Examples: lettuce, spinach, peas, broccoli, cabbage, kale, arugula, radishes, carrots. Benefits: extend season into spring/fall, often sweeter after frost, less pest pressure. Many can be overwintered in mild climates. Opposite of warm-season crops (tomatoes, peppers, squash) that need heat.',
    relatedTerms: ['Bolting'],
    searchableVariations: ['cool-season', 'cool season'],
  ),
  GardeningTerm(
    term: 'Crop Rotation',
    definition: 'Growing different plant families in different locations each year.',
    details: 'Prevents pest and disease buildup, balances soil nutrients. Basic 4-year rotation: Year 1: Legumes (fix nitrogen). Year 2: Heavy feeders (use nitrogen). Year 3: Light feeders. Year 4: Cover crop/fallow. By family: don\'t plant tomatoes where peppers/potatoes grew (same diseases). Plant families: Nightshades (tomatoes, peppers, eggplant, potatoes), Brassicas (cabbage, broccoli, kale), Legumes (beans, peas), Cucurbits (squash, cucumbers, melons), Alliums (onions, garlic).',
    relatedTerms: ['Heavy Feeder', 'Nitrogen Fixation'],
    searchableVariations: ['crop rotation'],
  ),
  GardeningTerm(
    term: 'Indeterminate',
    definition: 'Tomato plants that grow and produce continuously until killed by frost.',
    details: 'Indeterminate (vining) vs Determinate (bush) tomatoes: Indeterminate: grow 6-12+ feet tall, need strong support, produce tomatoes all season, remove suckers, best for fresh eating. Examples: Brandywine, Cherokee Purple, most heirlooms. Determinate: grow to 3-4 feet, bush form, ripen all at once over 2 weeks, keep suckers, good for canning/sauce, compact. Examples: Roma, Celebrity. Choose based on space and use.',
    relatedTerms: ['Suckers', 'Staking'],
    searchableVariations: ['indeterminate'],
  ),
  GardeningTerm(
    term: 'Frost Date',
    definition: 'The average date of the last spring frost or first fall frost in your area.',
    details: 'Critical for garden planning. Last spring frost: plant tender crops after this date. First fall frost: harvest tender crops before this date. Find your dates: search by zip code online, ask local extension office, ask experienced gardeners. Important: these are averages - actual dates vary by 2 weeks either way. Microclimates matter: valleys frost earlier, slopes and urban areas stay warmer. Track your actual frost dates over years.',
    relatedTerms: ['Hardiness Zone'],
    searchableVariations: ['frost date'],
  ),
  GardeningTerm(
    term: 'Hardiness Zone',
    definition: 'Geographic zones based on average annual minimum winter temperature.',
    details: 'USDA Plant Hardiness Zones range from 1 (coldest) to 13 (warmest), with a/b subdivisions. Each zone represents 10°F difference. Tells you: which perennials survive winter in your area, when to expect frost dates. Find your zone: USDA Plant Hardiness Zone Map online. Limitations: doesn\'t account for heat, humidity, rainfall, or microclimates. Most vegetables are annuals, so zone matters less than frost dates.',
    relatedTerms: ['Frost Date'],
    searchableVariations: ['hardiness zone'],
  ),
  GardeningTerm(
    term: 'Companion Planting',
    definition: 'Growing different plants together for mutual benefit.',
    details: 'Benefits include: pest control (marigolds repel aphids), trap crops (nasturtiums attract aphids away), beneficial insect attraction (dill attracts predatory wasps), improved growth (beans fix nitrogen for corn), space efficiency (tall crops shade heat-sensitive crops). Classic examples: Three Sisters (corn, beans, squash), tomatoes with basil, carrots with onions. Also avoid bad combinations: onions with beans, fennel with most plants.',
    relatedTerms: [],
    searchableVariations: ['companion planting'],
  ),
  GardeningTerm(
    term: 'Compost',
    definition: 'Decomposed organic matter used as a natural fertilizer and soil amendment.',
    details: 'Black gold for gardens! Benefits: improves soil structure, adds nutrients, increases water retention, feeds beneficial microbes, reduces waste. Making compost: mix "greens" (nitrogen: food scraps, grass clippings) with "browns" (carbon: leaves, straw) in 1:2 ratio. Keep moist, turn occasionally. Ready in 2-6 months. Using: add 1-2 inches to beds before planting, side-dress around plants, make compost tea. Don\'t compost: meat, dairy, diseased plants, weeds with seeds.',
    relatedTerms: ['Side-Dress', 'Mulching'],
    searchableVariations: ['compost', 'composting'],
  ),
  GardeningTerm(
    term: 'Staking',
    definition: 'Providing physical support structures for plants to grow upright.',
    details: 'Many vegetables need support to stay upright and productive. Types: Stakes - single pole for tomatoes, peppers. Cages - wire cylinders for determinate tomatoes, peppers. Trellises - flat or A-frame for cucumbers, beans, peas, squash. Benefits: saves space (vertical growing), improves air circulation, keeps fruit off ground (cleaner, less disease), easier harvest, prevents stem breakage. Install supports at planting time to avoid root damage. Train vines as they grow by gently weaving through or tying with soft material.',
    relatedTerms: ['Indeterminate'],
    searchableVariations: ['stake', 'staking', 'support', 'trellis', 'cage'],
  ),
  GardeningTerm(
    term: 'pH',
    definition: 'A measure of soil acidity or alkalinity on a scale from 0-14.',
    details: 'pH affects nutrient availability. Scale: 0-6.9 = acidic, 7 = neutral, 7.1-14 = alkaline. Most vegetables prefer slightly acidic soil (pH 6.0-7.0). Nutrient availability: some nutrients become unavailable at wrong pH. Blueberries need acidic (4.5-5.5), brassicas tolerate more alkaline (6.5-7.5). Test soil with pH meter or lab test. Adjust pH: add lime to raise pH (less acidic), add sulfur or peat moss to lower pH (more acidic). Changes take months, so plan ahead.',
    relatedTerms: [],
    searchableVariations: ['ph', 'acidity', 'alkaline', 'acidic'],
  ),
  GardeningTerm(
    term: 'Nitrogen Fixation',
    definition: 'The process by which legumes convert atmospheric nitrogen into plant-usable form.',
    details: 'Legumes (beans, peas, clover) have special relationship with Rhizobium bacteria. Bacteria colonize root nodules and "fix" atmospheric nitrogen (N2) into ammonia (NH3) that plants can use. Benefits: legumes need less fertilizer, improve soil for next crop, reduce nitrogen fertilizer costs. Crop rotation: plant nitrogen-hungry crops (corn, tomatoes, brassicas) after legumes. At season end: cut legume plants at soil level, leaving roots to decompose and release nitrogen. For best results: inoculate legume seeds with appropriate Rhizobium strain.',
    relatedTerms: ['Inoculating', 'Crop Rotation', 'Heavy Feeder'],
    searchableVariations: ['nitrogen fixation', 'nitrogen fixing', 'fix nitrogen'],
  ),
  GardeningTerm(
    term: 'Self-Pollinating',
    definition: 'Plants that can pollinate themselves without needing pollen from another plant.',
    details: 'Self-pollinating plants have both male and female parts in each flower, and can set fruit alone. Examples: tomatoes, peppers, beans, peas, lettuce. Benefits: don\'t need multiple plants for fruit production, true-to-type seeds (no cross-pollination). Cross-pollinating plants need pollen from another plant: squash, cucumbers, melons, corn. Blueberries are self-fertile but produce better with cross-pollination. Wind-pollinated (corn, spinach) or insect-pollinated (squash) still need pollinator transfer. For seed saving: self-pollinators are easier to keep pure.',
    relatedTerms: [],
    searchableVariations: ['self-pollinating', 'self-pollinate', 'cross-pollinate', 'pollinate', 'pollination'],
  ),
];
